### PR TITLE
WIP: Tech blog style (1st version)

### PR DESCRIPTION
**Pull request by skalka7**
In `_posts` there is a post I created just for testing purpose, I will delete when I will not need it anymore.
I will add some media queries soon to add responsive features, i don't have mockups for that so I will just go very basic. I guess we don't need a burger menu since we just show 2 logos.
Let's discuss this.

### CODE REVIEW

**Comment by skalka7** [comment]
About responsiveness: since this is a very simple design I think we just need to use one break point, I think that we need to pile items vertically when we go below 768px (iPad portrait mode). If you agree on this I can work on it.

**Comment by hilton** [comment]
How do I build the styles? I assume that SASS requires running something. Please add instructions to the README.

**Comment by frontendphil** [comment]
Wow 6000 lines added. Are you sure, we need all of that in version control or is some of that actually a dependency that can come from external sources?

**Comment by skalka7** [comment]
@hilton I use `jekyll serve` to compile, SASS files are compiled automatically since it's an official feature of Jekyll, that's why I didn't add anything to README. Options are defined in `_config.yml`.
@frontendphil Most of this lines are coming from [Susy](http://susydocs.oddbird.net/en/latest/), a library that I used. I guess we can include as dependency, I will check.

**Comment by hilton** [comment]
Ah, I wasn’t seeing the styles when looking at the generated HTML because of the absolute path in the `link` tag.

**Comment by frontendphil** [comment]
@skalka7 is this the `susy` you're using? http://susydocs.oddbird.net/en/latest/install/

**Comment by skalka7** [comment]
@frontendphil I'm aware of the issue with syntax highlighter, it doesn't work with inline code, I'm investigating. About the overflow: I saw this problem but I would like to ask your opinion about how to solve it (some people use scroll, some others cut the line).
@hilton Yes we need a link on signavio logo, will add it. I will style for tables too, I don't have a mockup but I guess I can do something similar to what we have on signavio.

**Comment by hilton** [comment]
By the way, I think that code blocks should use the full `div.container` width, because this is content that’s inherently wide, and we’re not using the space for anything else. Beyond that width, it should scroll.

**Comment by skalka7** [comment]
* Added link to signavio.com
* Fixed link to home on techblog logo
* Added style for tables
* Fixed issues with code highlighter
* added some media queries for small devices

**Comment by frontendphil** [comment]
@skalka7 but you didn't push ;) Next time turn each bullet point into a commit :P

**Comment by frontendphil** [comment]
What do you think about not adding too many grey boxes :) For instance with a table style more in that direction?

screen shot 2017-02-21 at 16 51 33

**Comment by skalka7** [comment]
I like your suggestion. Problem is that I didn't have any design direction here, I tried to get something similar on what we have on signavio.com, but more simple. Of course we can change it and make it even more simple.
In my opinion it doesn't make sense for me to try something without discussing about it before.
Let's collect all the suggestions, graphic ideas and so on so that I can finalize this.

**Comment by frontendphil** [comment]
Simple is good :) Everything here is to be considered discussion. So when I say "I think tables should look like this" that doesn't mean: Change it! Also we can tackle a lot of these problems when they arise. That means that the blog does not have to be perfect when we launch.

**Comment by skalka7** [comment]
I like your idea, maybe I would leave blackberry border after table head.

**Comment by hilton** [comment]
Is the `line-height: 1.5em` on code blocks intentional? It looks weirdly over-spaced.

**Comment by skalka7** [comment]
@hilton Yes, I did some tests and it looked good to me. On github is the same (`font-size:16px,line-height:24px`). We just have a smaller font size because I didn't add any monospaced font and `Courier New` is quite big.
One thing that we should check is the syntax highlighter, it has some issues, look at posts by Kat and Julius for example.

**Comment by hilton** [comment]
@skalka7 I see 12/20px on GitHub vs 13/24px on the tech blog.

**Comment by frontendphil** [comment]
From my side there are no issues that would be a deal breaker for a go-live. @hilton anything on your mind?

**Comment by hilton** [comment]
No, so I’ll merge.

**Pull request merged**
