### PR TITLE
New Blogpost: Raster image compression

### PR DESCRIPTION
**Pull request by sebastian-friedrich**
Hey, just fresh from the press, I would consider my blog post ready from a content perspective. Feedback is very welcome, probably need ot fix typos etc.

Can someone review?

### CODE REVIEW

**Comment by hilton** [comment]
The Slack channel, in general, and me, for example.

On a first read, it’s a good blog post and I wouldn’t change much. One suggestion: add Homebrew installation instructions for Mac users (I can look this up later).

There are also some typos: I can probably fix those in a commit tomorrow morning while travelling to Berlin.

**Comment by sebastian-friedrich** [comment]
Hey @hilton, thanks for checking the orthography and grammar.

Regarding Mac systems, I checked the script and it would also be possible to run it on Mac OSX, also zopfli build runs, as long as `command line tools` are installed (roughly what build-essential does in debian/ubuntu). I think the article is a little out of scope for people who are afraid of using some commands in a terminal. But you are right, I can imagine adding a little Mac user info in the end, basically saying:

* install command line tools like this: http://railsapps.github.io/xcode-command-line-tools.html
* install gifsicle with brew
* install git with brew

Regarding typography: Is there a reason why you changed the apostrophes? As far as I know I used the right ones: https://en.wikipedia.org/wiki/Apostrophe#Typographic_form

**Comment by hilton** [comment]
I replaced the ‘straight single quotes’, because we’re not using typewriters 😬

**Comment by sebastian-friedrich** [comment]
> I replaced the ‘straight single quotes’, because we’re not using typewriters 😬

pushed your changes?

BTW: I forgot to say - I am not sure whether installing `brew install zopfli` includes the extra tool _zopflipng_ ... that's why I'd like to stick to the repo.

**Comment by hilton** [comment]
I replaced quotes in https://github.com/signavio/tech-blog/pull/92/commits/88609de72aed690a6e2b25e710a9a3f954add5f3

**Comment by hilton** [comment]
Yes, `brew install zopfli` (i.e. https://github.com/google/zopfli) gives you the `zopflipng` tool.

**Comment by sebastian-friedrich** [comment]
Ok, was a little confused with the apostrophes by myself, I think we aim for the same ;-)

Added the brew setup stuff trusting in you that zopflipng is packed within it. I also added some further links to the Resources section, basically my sources of inspiration.

I'd consider it complete now, so if you agree with it, I think it's ready for take-off :-)

**Pull request merged**
